routes/admin.php
<?php
/** --------------------------------------------------------------------------------- */
/** --------------------------------------------------------------------------------- */
/** --------------- All the web backend routes are in below part -------------------- */
/** --------------------------------------------------------------------------------- */
/** --------------------------------------------------------------------------------- */

Route::get('route_list', function () {
    $routes = [];
    foreach (\Route::getRoutes()->getIterator() as $route) {
        if (strpos($route->uri, 'api') === false) {
            $routes[$route->uri] = $route->getName();
        }
    }
    dd($routes);
});

Route::get('set_vendor_access_permissions', '\App\Http\Controllers\Admin\UserController@set_vendor_access_permissions')->name('set_vendor_access_permissions');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'outlet']], function () {

    Route::resources([
        'pages' => 'PageController',
        'posts' => 'PostController',
        'medias' => 'MediaController',
        'upload' => 'ImageController',
        'users' => 'UserController',
        'routes' => 'RouteController',
        'album' => 'AlbumController'
    ]);

    // Namespace: \App\Http\Controllers\Admin\
    // URL Prefix: admin
    // Route name prefix: admin
    // middleware: auth,outlet
    // We will place here all the route that match this configuration...

    Route::get('routes/index', 'RouteController@index')->name('route.role_modify');
    Route::post('routes/index', 'RouteController@role_modify')->name('route.role_modify');

    // Media panel routes    
    Route::get('medias', 'MediaController@index')->name('medias.index');

    // users panel routes
    Route::post('search_users', 'UserController@index')->name('search_users');
    Route::get('modify_password_view/{id}', 'UserController@modify_password_view')->name('modify_password_view');
    Route::post('modify_password/{id}', 'UserController@modify_password')->name('modify_password');
    Route::get('vendor_url_existing', 'UserController@vendor_url_existing')->name('vendor_url');
    Route::get('modify_role_view/{id}', 'UserController@modify_role_view')->name('modify_role_view');
    Route::get('modify_role', 'UserController@modify_role')->name('modify_role');
    Route::post('modify_role', 'UserController@modify_role')->name('modify_role');
    Route::get('set_default_role/{id}', 'UserController@set_default_role')->name('set_default_role');

    // Slider  panel routes
    Route::get('sliders', 'SliderController@sliders')->name('sliders');
    Route::get('add_slider', 'SliderController@add_slider')->name('add_slider');
    Route::post('slider_save', 'SliderController@store')->name('slider_save');
    Route::get('edit_slider/{id}', 'SliderController@edit_slider')->name('edit_slider');
    Route::post('slider/{id}/update', 'SliderController@slider_update_save')->name('slider_update_save');
    Route::delete('slider_delete/{id}', 'SliderController@destroy')->name('slider_destroy');

    // Common Controller
    Route::get('common/team', 'CommonController@team')->name('common.team.index');
    Route::post('common/team/store', 'CommonController@teamStore')->name('common.team.store');
    Route::post('common/team/update/{id}', 'CommonController@teamUpdate')->name('common.team.update');
    Route::get('common/team/delete/{id}', 'CommonController@teamDelete')->name('common.team.delete');

    // Gallery
    Route::get('common/gallery', 'GalleryController@galleries')->name('common.gallery.index');
    Route::post('common/gallery/store', 'GalleryController@galleryStore')->name('common.gallery.store');
    Route::post('common/gallery/update/{id}', 'GalleryController@galleryUpdate')->name('common.gallery.update');
    Route::get('common/gallery/delete/{id}', 'GalleryController@galleryDelete')->name('common.gallery.delete');
    Route::post('common/gallery/serialUpdate', 'GalleryController@gallerySerialUpdate')->name('common.gallery.serialupdate');

    // Album Controller
    Route::get('common/album', 'AlbumController@index')->name('common.album.index');
    Route::post('common/album/store', 'AlbumController@store')->name('common.album.store');
    Route::put('common/album/update/{id}', 'AlbumController@update')->name('common.album.update');
    Route::get('common/album/delete/{id}', 'AlbumController@destroy')->name('common.album.delete');

    // Class Controller
    Route::get('common/classes', 'ClassesController@index')->name('common.class.index');
    Route::post('common/class/store', 'ClassesController@store')->name('common.class.store');
    Route::put('common/class/update/{id}', 'ClassesController@update')->name('common.class.update');
    Route::get('common/class/delete/{id}', 'ClassesController@destroy')->name('common.class.delete');

    // Subject Controller
    Route::get('common/subjects', 'SubjectsController@index')->name('common.subject.index');
    Route::post('common/subject/store', 'SubjectsController@store')->name('common.subject.store');
    Route::put('common/subject/update/{id}', 'SubjectsController@update')->name('common.subject.update');
    Route::get('common/subject/delete/{id}', 'SubjectsController@destroy')->name('common.subject.delete');

    // Video Controller
    Route::get('common/videos', 'VideosController@index')->name('common.video.index');
    Route::post('common/video/store', 'VideosController@store')->name('common.video.store');
    Route::put('common/video/update/{id}', 'VideosController@update')->name('common.video.update');
    Route::get('common/video/delete/{id}', 'VideosController@destroy')->name('common.video.delete');

    // All Single Routesvideo
    Route::get('htmlgen', 'HtmlGenController@index')->name('htmlgen');

    //ICT Lab Route
    Route::get('common/ictlab', 'IctlabController@index')->name('common.ictlab.index');
    Route::post('common/ictlab/store', 'IctlabController@store')->name('common.ictlab.store');
    Route::get('common/ictlab/edit/{id}', 'IctlabController@edit')->name('common.ictlab.edit');
    Route::post('common/ictlab/update/{id}', 'IctlabController@update')->name('common.ictlab.update');
    Route::get('common/ictlab/delete/{id}', 'IctlabController@destroy')->name('common.ictlab.delete');

    //Results Route
    Route::get('common/exam-results', 'ResultController@index')->name('common.exam-results.index');
    Route::post('common/exam-results/store', 'ResultController@store')->name('common.exam-results.store');
    Route::get('common/exam-results/edit/{id}', 'ResultController@edit')->name('common.exam-results.edit');
    Route::post('common/exam-results/update/{id}', 'ResultController@update')->name('common.exam-results.update');
    Route::get('common/exam-results/delete/{id}', 'ResultController@destroy')->name('common.exam-results.delete');

    //Institutions Route
    Route::get('common/institutions', 'InstitutionsController@index')->name('common.institutions.index');
    Route::post('common/institutions/store', 'InstitutionsController@store')->name('common.institutions.store');
    Route::get('common/institutions/edit/{id}', 'InstitutionsController@edit')->name('common.institutions.edit');
    Route::post('common/institutions/update/{id}', 'InstitutionsController@update')->name('common.institutions.update');
    Route::get('common/institutions/delete/{id}', 'InstitutionsController@destroy')->name('common.institutions.delete');

    //Training Session Registration User
    Route::get('common/tsession-registration', 'TrainingSessionRegistrationController@index')->name('common.tsession-registration.index');
    Route::get('common/tsession-registration/delete/{id}', 'TrainingSessionRegistrationController@destroy')->name('common.tsession-registration.delete');

    Route::get('common/tsession-registration/export-excel/', 'TrainingSessionRegistrationController@exportExcel')->name('common.tsession-registration.export_excel');


});


Route::middleware(['outlet'])->group(function () {
    // dashboard, menus, widgets
    Route::get('dashboard', ['uses' => '\App\Http\Controllers\Admin\DashboardController@index'])->name('dashboard');
    Route::get('menus', ['uses' => '\App\Http\Controllers\Admin\DashboardController@menus'])->name('menus');
    Route::get('widgets', '\App\Http\Controllers\Admin\DashboardController@widgets')->name('widgets');
    Route::post('widget_save', ['uses' => '\App\Http\Controllers\Admin\DashboardController@store'])->name('widget_save');
    Route::get('edit_widget/{id}', ['uses' => '\App\Http\Controllers\Admin\DashboardController@edit_widget'])->name('edit_widget');
    Route::post('widget/{id}/update', ['uses' => '\App\Http\Controllers\Admin\DashboardController@widget_update_save'])->name('widget_update_save');
    Route::delete('delete_widget/{id}', ['uses' => '\App\Http\Controllers\Admin\DashboardController@destroy']);
    // dashboard, menus, widgets close

    // terms/category management routes
    Route::get('terms', '\App\Http\Controllers\Admin\TermController@terms')->name('terms');
    Route::post('term_save', ['uses' => '\App\Http\Controllers\Admin\TermController@store'])->name('term_save');
    Route::get('edit_term/{id}', ['uses' => '\App\Http\Controllers\Admin\TermController@edit_term'])->name('edit_term');
    Route::post('term/{id}/update', ['uses' => '\App\Http\Controllers\Admin\TermController@term_update_save'])->name('term_update_save');
    Route::get('delete_term/{id}', ['uses' => '\App\Http\Controllers\Admin\TermController@destroy'])->name('delete_term');
    Route::get('get_categories_on_search', ['uses' => '\App\Http\Controllers\Admin\TermController@get_categories_on_search'])->name('get_categories_on_search');
   
    // ajax
    Route::get('/check_if_cat_url_exists', ['uses' => '\App\Http\Controllers\Admin\TermController@check_if_cat_url_exists'])->name('check_if_cat_url_exists');

    // setting management routes

routes/frontend.php
<?php

/** --------------------------------------------------------------------------------- */
/** --------------------------------------------------------------------------------- */
/** --------------- All the web frontend routes are in below part -------------------- */
/** --------------------------------------------------------------------------------- */
/** --------------------------------------------------------------------------------- */

// Main
Route::get('/page/{id}/{slug}', '\App\Http\Controllers\Site\HomeController@get_webpage')->name('webpage');
Route::get('/my_account', '\App\Http\Controllers\Site\CommonController@my_account')->name('my_account');
Route::get('/login_now', '\App\Http\Controllers\Site\CommonController@login_now')->name('login_now');
Route::get('/create_an_account', '\App\Http\Controllers\Site\CommonController@create_an_account')->name('create_an_account');
Route::post('/web_login', 'Auth\LoginController@login')->name('web_login');
Route::post('/web_signup', '\App\Http\Controllers\Site\CommonController@web_signup')->name('web_signup');
Route::get('/logout', 'Auth\LoginController@logout')->name('web_logout');


Route::get('/', '\App\Http\Controllers\Site\HomeController@index');

/** --------------- Nipun ----------
 * T School Pages route List
 -----------------------------------**/

//Gallery Photo
Route::get('/albums/{id}', '\App\Http\Controllers\Site\GalleryController@albumPhoto')->name('album_photos');
Route::get('/page/photos', '\App\Http\Controllers\Site\GalleryController@photos')->name('gallery_photos');
Route::get('/page/photos/{id}', '\App\Http\Controllers\Site\GalleryController@photos')->name('gallery_photos');

//Quote Page
Route::get('/page/quote', '\App\Http\Controllers\Site\TschoolController@pageQuote')->name('page_quote');
Route::get('/page/quote/load/{id}', '\App\Http\Controllers\Site\TschoolController@pageSingleQuote')->name('page_single_quote');

//Administation Page
Route::get('page/administration', '\App\Http\Controllers\Site\TschoolController@pageAdministration')->name('page_administration');
Route::post('page/administration', '\App\Http\Controllers\Site\TschoolController@pageAdministration')->name('page_administration');

//Result Page
Route::get('page/result', '\App\Http\Controllers\Site\TschoolController@pageResult')->name('page_result');
Route::post('page/result', '\App\Http\Controllers\Site\TschoolController@pageResult')->name('page_result');

//News Page
Route::get('page/news', '\App\Http\Controllers\Site\TschoolController@pageNews')->name('page_news');
Route::get('page/news/load/{id}', '\App\Http\Controllers\Site\TschoolController@pageSingleNews')->name('page_single_news');
Route::get('page/news/category/{id}', '\App\Http\Controllers\Site\TschoolController@pageArchiveNews')->name('page_archive_news');


//Video Page
Route::get('page/video', '\App\Http\Controllers\Site\TschoolController@pageVideo')->name('page_video');
Route::get('page/video-search', '\App\Http\Controllers\Site\TschoolController@pageVideoSearch')->name('page_video_search');
Route::get('page/video/load/{id}', '\App\Http\Controllers\Site\TschoolController@pageSingleVideo')->name('page_single_video');


//Subject Video [Homepage grid]
Route::get('page/video/subject/{id}', '\App\Http\Controllers\Site\TschoolController@pageSubjectVideo')->name('page_video_subject');

/* -----------Tschool Teacher List --------*/

//Headmaster List
Route::get('page/tlist-headmaster', '\App\Http\Controllers\Site\TschoolController@pageTeacherListHeadmaster')->name('page_teacher_list_headmaster');
Route::post('page/tlist-headmaster', '\App\Http\Controllers\Site\TschoolController@pageTeacherListHeadmaster')->name('page_teacher_list_headmaster');


//ICT4E  Ambassador list
Route::get('page/tlist-ict4e-ambassador', '\App\Http\Controllers\Site\TschoolController@pageTeacherListIctAmbassador')->name('page_teacher_list_ict4e_ambassador');
Route::post('page/tlist-ict4e-ambassador', '\App\Http\Controllers\Site\TschoolController@pageTeacherListIctAmbassador')->name('page_teacher_list_ict4e_ambassador');

//All Teacher list
Route::get('page/teacher', '\App\Http\Controllers\Site\TschoolController@pageAllTeacherList')->name('page_teacher_list_all');
Route::post('page/teacher', '\App\Http\Controllers\Site\TschoolController@pageAllTeacherList')->name('page_teacher_list_all');



//All ICT LAb
Route::get('page/ictlab', '\App\Http\Controllers\Site\TschoolController@pageIctLabList')->name('page_ict_lab');
Route::post('page/ictlab', '\App\Http\Controllers\Site\TschoolController@pageIctLabList')->name('page_ict_lab');

//All institutions
Route::get('page/institutions', '\App\Http\Controllers\Site\TschoolController@pageInstitutions')->name('page_institutions');
Route::post('page/institutions', '\App\Http\Controllers\Site\TschoolController@pageInstitutions')->name('page_institutions');




//Training Session Registrtion
Route::get('page/traning-session-registration', '\App\Http\Controllers\Site\TschoolController@TraningSessionRegistration')->name('page_traning_session_registration');
Route::post('page/traning-session-registration/store', '\App\Http\Controllers\Site\TschoolController@TraningSessionRegistrationstore')->name('page_traning_session_registration_store');

routes/web.php
<?php
use Illuminate\Support\Facades\Artisan;

Auth::routes();

use App\Http\Resources\Route;
use Illuminate\Http\Request;


// Role based routes
require_once 'admin.php';
require_once 'frontend.php';

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = ['media_id','category_id','serial','caption','active'];


    public function image()
    {
        return $this->hasOne(Image::class,'id','media_id');
    }
}

app/Http/Controllers/Admin/CommonController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Gallery\GalleryInterface;

class CommonController extends Controller
{


    private $request;
    private $gallery;

    public function __construct(Request $request, GalleryInterface $gallery)
    {
        $this->request = $request;
        $this->gallery = $gallery;
    }

    public function galleries()
    {
        $gallery = $this->gallery->getAll();
        $image = false;

        if ($this->request->id) {
            $image = $this->gallery->getById($this->request->id);
        }

        return response()->view('admin.common.gallery.index',compact('gallery','image'));
    }


    public function galleryStore()
    {

        $existedGallery = \App\Gallery::orderBy('serial','DESC')->first();
        $serial = ($existedGallery->serial??0)+1;

        $attr  = [
            'media_id' => $this->request->imageId,
            'category_id' => null,
            'serial' => $serial,
            'caption' => $this->request->caption,
            'active' => $this->request->active
        ];

        $this->gallery->create($attr);

        return redirect()->back();
    }


    public function galleryUpdate($id)
    {
        $gallery = $this->gallery->getById($id);
        $gallery->media_id = $this->request->imageId;
        $gallery->category_id = null;
        $gallery->caption = $this->request->caption;
        $gallery->active = $this->request->active;
        $gallery->save();

        return redirect()->back();
    }


    public function galleryDelete($id)
    {
        $gallery = $this->gallery->delete($id);
        
        return redirect()->back();
    }


    public function gallerySerialUpdate(Request $request) {

        $datas = $request->get('item');

        foreach($datas as $data) {
            $gallery = $this->gallery->getById($data['id']);
            $gallery->serial = $data['serial'];
            $gallery->save();            
        }
    }

}

resources/views/admin/common/gallery/index.blade.php
@extends('layouts.app')
@section('title', 'Gallery')
@section('sub_title', 'all images')
@section('content')
    <?php
            //dd($image);
    ?>
    <div class="row">
        @if(Session::has('success'))
            <div class="col-md-12">
                <div class="callout callout-success">
                    {{ Session::get('success') }}
                </div>
            </div>
        @endif

        @if($errors->any())
            <div class="col-md-12">
                <div class="callout callout-danger">
                    <h4>Warning!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <div class="col-md-3" id="signupForm">
            @component('component.form')
                @slot('form_id')
                    @if (!empty($image->id))
                        schedule_form333
                    @else
                        schedule_form333
                    @endif
                @endslot
                @slot('title')
                    Add/Edit
                @endslot

                @slot('route')
                    {{!empty($image->id)?route('admin.common.gallery.update',$image->id):route('admin.common.gallery.store')}}
                @endslot

                @slot('method')
                    {{-- @if (!empty($team->id))
                        {{ method_field('put') }}
                    @endif --}}
                @endslot

                @slot('fields')

                    <div class="form-group">
                        {{ Form::label('imageId', 'Image ID', array('class' => 'imageId')) }}
                        {{ Form::text('imageId', $image->media_id??'', ['required', 'class' => 'form-control', 'placeholder' => 'Enter ID...']) }}
                        @if($image->image??false)
                            <div><img src="{{asset($image->image->icon_size_directory)}}" width="80"/></div>
                        @endif
                    </div>

                    <div class="form-group">
                        {{ Form::label('caption', 'Caption', array('class' => 'uri')) }}
                        {{ Form::textarea('caption', $image->caption??'', ['', 'class' => 'form-control', 'placeholder' => 'Enter caption...']) }}
                    </div>

                    <div class="form-group">
                        {{Form::label('album','Album',array('class' => 'album'))}}
                        <?php
                            $albums = \App\Album::select('id', 'name')->get();
                        ?>
                        <select class="form-control" name="album_id">
                            @foreach($albums as $album)
                                <option value="{{ $album->id }}" {{ (!empty($image->category_id) && $image->category_id == $album->id) ? 'selected="selected"' : '' }}>
                                    {{ $album->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        {{Form::label('status','Status',array('class' => 'status'))}}
                        {!! Form::select('active', [0 => 'Disable', 1 => 'Active'], $image->active??1,['class' => 'form-control']) !!}
                    </div>

                @endslot
            @endcomponent
        </div>
        <div class="col-md-9">

            <div class="box box-success">
                <div class="box-header with-border">
                    Images <a href="{{route('admin.common.gallery.index')}}" class="btn btn-xs btn-success"><i
                                class="fa fa-plus"></i></a>
                </div>
                <div class="box-body" style="">
                    <div class="box-body table-responsive no-padding" id="reload_me">
                        <table class="table table-hover" id="for_reloader">
                            <tr>
                                <th>Serial No</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Caption</th>
                                <th>Album</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            <tbody id="myTable">
                            @foreach($gallery as $gal)
                                <tr class="item" data-id="{{$gal->id}}">
                                    <td class="index">{{$gal->serial}} </td>
                                    <td><img src="{{asset(($gal->image->icon_size_directory??''))}}" width="100"/></td>
                                    <td>{{$gal->image->original_name??''}}</td>
                                    <td>{{$gal->caption??''}}</td>
                                    <td>
                                        @php
                                        $albumName = \App\Album::where('id', $gal->category_id)->get();
                                        // dump($albumName)
                                        @endphp

                                        @if(!empty($albumName[0]))
                                            {{$albumName[0]->name}}
                                        @endif


                                    </td>
                                    <td>
                                        @if($gal->active??false)
                                            Active
                                        @else
                                            Disable
                                        @endif
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-primary"
                                           href="{{ route('admin.common.gallery.index')  }}?id={{$gal->id}}">
                                            <i class="fa fa-pencil-square-o"></i>
                                        </a>
                                        <a class="btn btn-xs btn-danger"
                                           href="{{ route('admin.common.gallery.delete',$gal->id)  }}">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>


                        <div class="box-footer clearfix">
                            {{ $gallery->links('component.paginator', ['object' => $gallery]) }}
                        </div>
                    </div>

                </div>
                <div class="box-footer clearfix">
                </div>
            </div>
        </div>
    </div>


@endsection



@push('scripts')
    <script type="text/javascript">
        jQuery('#myTable').sortable({
            axis: 'y',
            update: function (event, ui) {
                var data = jQuery(".item"),
                    item = []


                jQuery.each(data, function (index, itm) {
                    var autoid = itm.dataset.id;
                    var serial = index + 1;

                    item.push({
                        serial: serial,
                        id: autoid
                    });

                    //console.log(jQuery(itm)[0])
                });

                jQuery.ajax({
                    data: {
                        "_token": "{{ csrf_token() }}",
                        "item": item
                    },
                    type: 'POST',
                    url: '{{ route('admin.common.gallery.serialupdate') }}',
                    success: function (result) {
                        // jQuery('#reload_me').load('{{ route('admin.common.gallery.index') }}' + " " + '#reload_me');
                        location.reload(true);
                        jQuery('#myTable').sortable();
                    }
                });
            }
        });
    </script>
    <style>
        td:hover {
            cursor: move;
        }
    </style>
@endpush